import Head from 'next/head';
import Image from 'next/image';
import PCPart from '../components/PCPart';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.title}>Learn Hardware</div>
      <div className={styles.description}>
        We have created this website for students (and other people) to learn about computer hardware enough to build a PC themselves! The 3D models are supposed to provide a better understanding and idea of what the component really is.
      </div>
      <PCPart
        url="https://go.echoar.xyz/9hVH"
        heading="CPU"
        text="A central processing unit, also called a central processor, main processor or just processor, is the electronic circuitry that executes instructions comprising a computer program. The CPU performs basic arithmetic, logic, controlling, and input/output operations specified by the instructions in the program."
      />
      <PCPart
        url="https://go.echoar.xyz/1Ypm"
        heading="Motherboard"
        text="A motherboard is the main printed circuit board in general-purpose computers and other expandable systems. It holds and allows communication between many of the crucial electronic components of a system, such as the central processing unit and memory, and provides connectors for other peripherals."
      />
      <PCPart
        url="https://go.echoar.xyz/bSFg"
        heading="GPU"
        text="A graphics processing unit is a specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display device. GPUs are used in embedded systems, mobile phones, personal computers, workstations, and game consoles."
      />
      <PCPart
        url="https://go.echoar.xyz/7X82"
        heading="Heat Sink"
        text="A heat sink is a passive heat exchanger that transfers the heat generated by an electronic or a mechanical device to a fluid medium, often air or a liquid coolant, where it is dissipated away from the device, thereby allowing regulation of the device's temperature."
      />
      <PCPart
        url="https://go.echoar.xyz/NN3u"
        heading="Power Supply"
        text="A power supply is an electrical device that supplies electric power to an electrical load. The primary function of a power supply is to convert electric current from a source to the correct voltage, current, and frequency to power the load. "
      />
      <PCPart
        url="https://go.echoar.xyz/5idQ"
        heading="Solid State Drive"
        text="A solid-state drive is a solid-state storage device that uses integrated circuit assemblies to store data persistently, typically using flash memory, and functioning as secondary storage in the hierarchy of computer storage."
      />
      <PCPart
        url="https://go.echoar.xyz/z5FT"
        heading="Memory"
        text="In computing, memory is a device or system that is used to store information for immediate use in a computer or related computer hardware and digital electronic devices. The term memory is often synonymous with the term primary storage or main memory. An archaic synonym for memory is store."
      />
      <PCPart
        url="https://go.echoar.xyz/Dk6T"
        heading="Case"
        text="A computer case, also known as a computer chassis, tower, system unit, or cabinet, is the enclosure that contains most of the components of a personal computer. Cases are usually constructed from steel, aluminium and plastic."
      />
      <PCPart
        url="https://go.echoar.xyz/c5DT"
        heading="Peripherals"
        text="A peripheral or peripheral device is an auxiliary device used to put information into and get information out of the computer. For example a keyboard, a mouse or a monitor"
      />
      <PCPart
        url="https://go.echoar.xyz/qp7T"
        heading="Complete Build"
        text="Here is a complete computer build demonstrated in 3D"
      />
    </div>
  );
}
